/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.PICTENS.view;

import java.sql.SQLException;
import project.PICTENS.error.PelangganException;

/**
 *
 * @author IantReza
 */
public class MainHomeView extends javax.swing.JFrame {

    /**
     * Creates new form MainHomeVieww
     */
    private static String userName;
    
    public MainHomeView(String us) {
        initComponents();
        
        userName = us;
        selamatDatangTxt.setText("Welcome, "+userName);
    }

    public void loadDataase() throws SQLException, PelangganException {
        homeView1.loadDataase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goLoginBtn = new javax.swing.JButton();
        selamatDatangTxt = new javax.swing.JLabel();
        homeView1 = new project.PICTENS.view.HomeView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goLoginBtn.setBackground(new java.awt.Color(174, 174, 176));
        goLoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        goLoginBtn.setForeground(new java.awt.Color(53, 54, 58));
        goLoginBtn.setText("LOGOUT");
        goLoginBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 54, 58)));
        goLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goLoginBtnMouseClicked(evt);
            }
        });
        goLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goLoginBtnloginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(goLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 120, 36));

        selamatDatangTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selamatDatangTxt.setForeground(new java.awt.Color(174, 174, 176));
        getContentPane().add(selamatDatangTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 590, 30));
        getContentPane().add(homeView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goLoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goLoginBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_goLoginBtnMouseClicked

    private void goLoginBtnloginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goLoginBtnloginBtnActionPerformed
        // TODO add your handling code here:
        LoginView login = new LoginView();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goLoginBtnloginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goLoginBtn;
    private project.PICTENS.view.HomeView homeView1;
    private javax.swing.JLabel selamatDatangTxt;
    // End of variables declaration//GEN-END:variables
}
