package project.PICTENS.view;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author IantReza
 */
public class RegisView extends javax.swing.JFrame {

    private String username;
    private String pass;

    /**
     * Creates new form RegisView
     */
    public RegisView() {
        initComponents();

    }

    public String getPass() {
        return pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

    public JPasswordField getPasswordField() {
        return passwordField;
    }

    public JTextField getUsernameFieldTxt() {
        return usernameFieldTxt;
    }

    private void btnReset() {
        RegisView regisView = new RegisView();
        regisView.setVisible(false);
    }

    private void btnLogin() {
        btnReset();
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
        this.setVisible(false);
    }

    public void resetText(JTextField text, String same) {
        if (text.getText().equals(same)) {
            text.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        usernameFieldTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        registBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameFieldTxt.setBackground(new java.awt.Color(174, 174, 176));
        usernameFieldTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameFieldTxt.setForeground(new java.awt.Color(53, 54, 58));
        usernameFieldTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(53, 54, 58)));
        jPanel2.add(usernameFieldTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 237, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("REGISTER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("User Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        passwordField.setBackground(new java.awt.Color(174, 174, 176));
        passwordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(53, 54, 58));
        passwordField.setText("jPasswordField1");
        passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(53, 54, 58)));
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        jPanel2.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 237, -1));

        registBtn.setBackground(new java.awt.Color(174, 174, 176));
        registBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registBtn.setForeground(new java.awt.Color(53, 54, 58));
        registBtn.setText("REGISTER");
        registBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 54, 58)));
        registBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registBtnActionPerformed(evt);
            }
        });
        jPanel2.add(registBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 237, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/PICTENS/view/RegisterForm.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 54, 58)));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registBtnActionPerformed
        // TODO add your handling code here:
        username = usernameFieldTxt.getText();
        pass = passwordField.getText();
        JOptionPane.showMessageDialog(null, "Pendaftaran berhasil silakan lakukan login");
        btnReset();
        btnLogin();
    }//GEN-LAST:event_registBtnActionPerformed

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        // TODO add your handling code here:
        resetText(passwordField, "jPasswordField1");
    }//GEN-LAST:event_passwordFieldMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registBtn;
    private javax.swing.JTextField usernameFieldTxt;
    // End of variables declaration//GEN-END:variables
}
